#!/usr/bin/env ruby

require "yaml"
require "./lib-dups.rb"

HELPTEXT = <<HELP
Usage: find-duplicates.rb <hashdb.yaml>*

Finds exact duplicates in the given hashdb files.
This scripts does not alter any files but merely outputs YAML containing the
duplicates.
Use other scripts such as `rm-duplicates.rb` to process the duplicates based
on the output of this script.

Arguments:
  hashdb.yaml: One or more files containing a hashdb generated by
               create-hashdb.rb.
HELP

if ARGV.length < 1 || ARGV.include?("--help") || ARGV.include?("-h")
  puts HELPTEXT
  exit 1
end

invdb = {}

db = cleanup_db(merge_dbs(ARGV))

db.each do |k,v|
  invdb[v["sha"]] ||= []
  invdb[v["sha"]].push(k)
end

i = 0
invdb.each_with_index do |kv|
  v = kv[1]

  if v.length > 1
    remove_false_positives(db, v).each do |d|
      print_dups(i, d)
      i += 1
    end
  end
end
