#!/usr/bin/env ruby

require "yaml"

HELPTEXT = <<HELP
Usage: mark-unequal.rb <hashdb.yaml> <duplicates-output.yaml> [--dry]

Marks files in a hashdb to be unequal for later (visual) duplicate comparison.
This allows to manually reduce the number of false positives.
To use, manually clean up the ouput of a duplicate finder so only the false
positives remain and pass this to mark-unequal.rb.

Arguments:
             hashdb.yaml: A file containing a hashdb generated by
                          create-hashdb.rb that should be updated.
  duplicates-output.yaml: A file containing the output generated by
                          find-duplicates.rb or find-visual-duplicates.rb.
                   --dry: If passed, no changes will be written to hashdb.yaml.
HELP

if ARGV.length < 2
  puts HELPTEXT
  exit 1
end

HASHDB = ARGV[0]
DUPS_FILE = ARGV[1]
DRY = ARGV.include? "--dry"

db = YAML.load(File.read(HASHDB))

dups = YAML.load(File.read(DUPS_FILE))

dups.each do |k, v|
  puts "Setting unequals of #{v[0]}..."

  v.combination(2).each do |e|
    e.sort!
    db[e[0]]["unequal_to"] ||= {}
    db[e[0]]["unequal_to"][e[1]] = { "mtime" => File.mtime(e[1]).to_f }
  end
end

unless DRY
  File.open(HASHDB, 'w') { |f| f.write YAML.dump(db) }
end
