#!/usr/bin/env ruby

require "yaml"
require "fileutils"

if ARGV.length < 1 || ARGV.include?("--help") || ARGV.include?("-h")
  puts "Usage: rm-duplicates <duplicates-output.yaml> [rm]"
  puts
  puts "Removes duplicate images from the filesystem."
  puts
  puts "Arguments:"
  puts "  duplicates-output.yaml: A file containing the output generated by"
  puts '                          find-duplicates.rb or find-visual-duplicates.rb.'
  puts "                      rm: If specified, the duplicate files will be removed."
  puts "                          Otherwise, only the paths will be printed (\"dry run\")."
  exit 1
end

YAML.load(File.read(ARGV[0])).each do |k, dups|
  dups[1..-1].each do |f|
    puts f
    FileUtils.rm(f) if ARGV[1] == "rm"
  end
end
