#!/usr/bin/env ruby

require "yaml"

if ARGV.length < 1 || ARGV.include?("--help") || ARGV.include?("-h")
  puts "Usage: show-duplicates.rb <duplicates-output.yaml>"
  puts
  puts "Opens an eog image viewer instance for every duplicate so you can check them"
  puts "easily."
  puts
  puts "Arguments:"
  puts "  duplicates-output.yaml: A file containing the output generated by"
  puts "                          find-duplicates.rb or find-visual-duplicates.rb."
  exit 1
end

YAML.load(File.read(ARGV[0])).each do |k, dups|
  puts k
  `eog "#{dups.join('" "')}"`
end
